---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-deployment
  labels:
    app: campground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campground
  template:
    metadata:
      labels:
        app: campground
    spec:
      containers:
      - name: yelp-camp
        image: hemendra05/yelp-camp:1.3
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: yelp-service
spec:
  type: NodePort
  selector:
    app: campground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
